"""Updated task

Revision ID: 2d6f60c8be11
Revises: 857187806a5c
Create Date: 2025-04-10 07:50:34.496838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6f60c8be11'
down_revision: Union[str, None] = '857187806a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('pid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['pid'], ['id'])
    op.drop_column('task', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'pid')
    # ### end Alembic commands ###
